// <auto-generated />
using System;
using FinancialReportAnalyzer.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialReportAnalyzer.Web.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107");

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Industry = "IT",
                            Name = "Техносфера"
                        },
                        new
                        {
                            Id = 2,
                            Industry = "Агро",
                            Name = "Агрохолдинг 'Степи України'"
                        },
                        new
                        {
                            Id = 3,
                            Industry = "Промисловість",
                            Name = "Металург"
                        });
                });

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.FinancialMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SavedReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SavedReportId");

                    b.ToTable("FinancialMetrics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MetricName = "дохід",
                            MetricValue = 1500000m,
                            SavedReportId = 1
                        },
                        new
                        {
                            Id = 2,
                            MetricName = "витрати",
                            MetricValue = 950000m,
                            SavedReportId = 1
                        },
                        new
                        {
                            Id = 3,
                            MetricName = "прибуток",
                            MetricValue = 500000m,
                            SavedReportId = 1
                        },
                        new
                        {
                            Id = 4,
                            MetricName = "збиток",
                            MetricValue = 50000m,
                            SavedReportId = 1
                        },
                        new
                        {
                            Id = 5,
                            MetricName = "активи",
                            MetricValue = 2300000m,
                            SavedReportId = 1
                        },
                        new
                        {
                            Id = 6,
                            MetricName = "пасиви",
                            MetricValue = 800000m,
                            SavedReportId = 1
                        });
                });

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReportTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "Квартальний (Q1)"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "Квартальний (Q2)"
                        },
                        new
                        {
                            Id = 3,
                            TypeName = "Річний"
                        },
                        new
                        {
                            Id = 4,
                            TypeName = "Півріччя"
                        });
                });

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.SavedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReportTypeId");

                    b.ToTable("SavedReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnalyzedAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = 1,
                            ReportTypeId = 4,
                            Title = "Звіт 'Техносфера' за півріччя 2025"
                        });
                });

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.FinancialMetric", b =>
                {
                    b.HasOne("FinancialReportAnalyzer.Web.Models.SavedReport", "SavedReport")
                        .WithMany("Metrics")
                        .HasForeignKey("SavedReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedReport");
                });

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.SavedReport", b =>
                {
                    b.HasOne("FinancialReportAnalyzer.Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialReportAnalyzer.Web.Models.ReportType", "ReportType")
                        .WithMany()
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("FinancialReportAnalyzer.Web.Models.SavedReport", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
